name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Navigate to the React app subdirectory
      - name: Change directory to React app
        run: cd climate-search-engine

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          cd climate-search-engine
          npm install

      # Step 5: Build the React app
      - name: Build
        run: |
          cd climate-search-engine
          npm run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: climate-search-engine/dist
